### ISSUE TITLE
RuntimeException when running scenario in an IDE

### ISSUE THREAD

**Issue by vvalencia-cl** [udaychandra/bdd#5]
version: 0.1.0

Environment:
* IntelliJ IDEA 2018.3.4
* Ubuntu 18.10
* OpenJDK 1.11.0
* JUnit 5.3.2

Running the suite with maven, everything works ok.

But, when executing the test directly in the IDE (Run TheTestClass), 
The scerario runs ok, but the tests result isn't, because the bbb-reports dir couldn't be generated.

This is error reported:

```
java.lang.ExceptionInInitializerError
	at io.github.udaychandra.bdd.ext.StoryExtension.afterAll(StoryExtension.java:62)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllCallbacks$11(ClassTestDescriptor.java:396)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllCallbacks$12(ClassTestDescriptor.java:396)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeAfterAllCallbacks(ClassTestDescriptor.java:396)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:221)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:74)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:118)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:118)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: Unable to create the folder for saving bdd reports.
	at io.github.udaychandra.bdd.writer.BasicStoryWriter.<clinit>(BasicStoryWriter.java:63)
	... 30 more
```

This is the location where it tries to generate the reports dir:

`file:/home/user/.m2/repository/org/junit/platform/junit-platform-commons/1.3.2/junit-platform-commons-1.3.2.jar!/META-INF/versions/bdd-reports`

**Comment by udaychandra** [comment]
Can you provide your maven pom file or provide a reproducer?

**Comment by vvalencia-cl** [comment]
[bdd-ide-problem-issue-5.zip](https://github.com/udaychandra/bdd/files/2910717/bdd-ide-problem-issue-5.zip)

I've created a simple project that has only one bdd test. This reproduces the problem.

`➜  bdd-ide-problem-issue-5 mvn package
executing mvnw instead of mvn
Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< cl.vvalencia:bdd-ide-problem-issue-5 >----------------
[INFO] Building bdd-ide-problem-issue-5 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bdd-ide-problem-issue-5 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vvalencia/dev/git-ext/bdd-ide-problem-issue-5/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ bdd-ide-problem-issue-5 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ bdd-ide-problem-issue-5 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vvalencia/dev/git-ext/bdd-ide-problem-issue-5/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ bdd-ide-problem-issue-5 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/vvalencia/dev/git-ext/bdd-ide-problem-issue-5/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ bdd-ide-problem-issue-5 ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running cl.vvalencia.UserRegistrationIntegrationTest
finish: token2
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 s - in cl.vvalencia.UserRegistrationIntegrationTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ bdd-ide-problem-issue-5 ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/vvalencia/dev/git-ext/bdd-ide-problem-issue-5/target/bdd-ide-problem-issue-5-0.0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.457 s
[INFO] Finished at: 2019-02-27T11:37:09-03:00
[INFO] ------------------------------------------------------------------------
`

And in IDEA

![screenshot from 2019-02-27 11-40-53](https://user-images.githubusercontent.com/1178505/53498173-92882200-3a84-11e9-81fe-11ea104d7791.png)

**Comment by udaychandra** [comment]
Thank you for adding a reproducer. A fix has been pushed and released in v0.1.1

**Comment by vvalencia-cl** [comment]
Thank you so much!

Checked version 0.1.1 and it's working

**Comment by udaychandra** [comment]
Fix verified.
